/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AanwezighedenSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'spelerId', 'status', 'trainingId', 'updatedAt'] as const
  $columns = AanwezighedenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare spelerId: number
  @column()
  declare status: string
  @column()
  declare trainingId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ActiviteitenSchema extends BaseModel {
  static $columns = ['createdAt', 'datum', 'eindtijd', 'heleDag', 'herhaal', 'herhaalTot', 'id', 'locatie', 'notitie', 'soort', 'tijd', 'titel', 'updatedAt'] as const
  $columns = ActiviteitenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare datum: DateTime
  @column()
  declare eindtijd: string | null
  @column()
  declare heleDag: boolean
  @column()
  declare herhaal: string | null
  @column.date()
  declare herhaalTot: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare locatie: string | null
  @column()
  declare notitie: string | null
  @column()
  declare soort: string
  @column()
  declare tijd: string | null
  @column()
  declare titel: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class DoelenSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'omschrijving', 'spelerId', 'status', 'updatedAt', 'voortgang'] as const
  $columns = DoelenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare omschrijving: string
  @column()
  declare spelerId: number
  @column()
  declare status: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare voortgang: number
}

export class DoelpuntenSchema extends BaseModel {
  static $columns = ['assistSpelerId', 'createdAt', 'id', 'minuut', 'scorerSpelerId', 'updatedAt', 'wedstrijdId'] as const
  $columns = DoelpuntenSchema.$columns
  @column()
  declare assistSpelerId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare minuut: number | null
  @column()
  declare scorerSpelerId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare wedstrijdId: number
}

export class FormatySchema extends BaseModel {
  static $columns = ['createdAt', 'formatie', 'id', 'naam', 'toewijzing', 'updatedAt'] as const
  $columns = FormatySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare formatie: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare naam: string
  @column()
  declare toewijzing: any | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class InstellingenSchema extends BaseModel {
  static $columns = ['accent', 'clubNaam', 'createdAt', 'id', 'logoPath', 'seizoen', 'teamNaam', 'thema', 'updatedAt'] as const
  $columns = InstellingenSchema.$columns
  @column()
  declare accent: string | null
  @column()
  declare clubNaam: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare logoPath: string | null
  @column()
  declare seizoen: string
  @column()
  declare teamNaam: string
  @column()
  declare thema: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class KaartenSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'minuut', 'spelerId', 'type', 'updatedAt', 'wedstrijdId'] as const
  $columns = KaartenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare minuut: number | null
  @column()
  declare spelerId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare wedstrijdId: number
}

export class LiveeventSchema extends BaseModel {
  static $columns = ['createdAt', 'details', 'id', 'minuut', 'spelerId', 'type', 'updatedAt', 'wedstrijdId'] as const
  $columns = LiveeventSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare details: any | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare minuut: number | null
  @column()
  declare spelerId: number | null
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare wedstrijdId: number
}

export class OefeningenSchema extends BaseModel {
  static $columns = ['categorie', 'createdAt', 'doel', 'favoriet', 'id', 'naam', 'tekening', 'type', 'updatedAt'] as const
  $columns = OefeningenSchema.$columns
  @column()
  declare categorie: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare doel: string | null
  @column()
  declare favoriet: boolean
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare naam: string
  @column()
  declare tekening: any | null
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class OnderdelenSchema extends BaseModel {
  static $columns = ['aandachtspunten', 'aantalSpelers', 'beschrijving', 'createdAt', 'doel', 'duur', 'id', 'materialen', 'naam', 'oefeningId', 'tekening', 'trainingId', 'type', 'updatedAt', 'veldGrootte'] as const
  $columns = OnderdelenSchema.$columns
  @column()
  declare aandachtspunten: string | null
  @column()
  declare aantalSpelers: number | null
  @column()
  declare beschrijving: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare doel: string | null
  @column()
  declare duur: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare materialen: string | null
  @column()
  declare naam: string
  @column()
  declare oefeningId: number | null
  @column()
  declare tekening: any | null
  @column()
  declare trainingId: number
  @column()
  declare type: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare veldGrootte: string | null
}

export class OpgaveSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'reden', 'spelerId', 'updatedAt', 'wedstrijdId'] as const
  $columns = OpgaveSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare reden: string | null
  @column()
  declare spelerId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare wedstrijdId: number
}

export class OpstellingrijenSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'minuten', 'positieId', 'positieLabel', 'spelStatus', 'spelerId', 'updatedAt', 'wedstrijdId'] as const
  $columns = OpstellingrijenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare minuten: number
  @column()
  declare positieId: string
  @column()
  declare positieLabel: string
  @column()
  declare spelStatus: string
  @column()
  declare spelerId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare wedstrijdId: number
}

export class RapportenSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'ovr', 'positie', 'seizoen', 'skills', 'soort', 'spelerId', 'sterren', 'tekst', 'updatedAt'] as const
  $columns = RapportenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ovr: number | null
  @column()
  declare positie: string | null
  @column()
  declare seizoen: string
  @column()
  declare skills: any | null
  @column()
  declare soort: string
  @column()
  declare spelerId: number
  @column()
  declare sterren: any | null
  @column()
  declare tekst: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ReviewSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'spelerId', 'tekst', 'updatedAt', 'wedstrijdId'] as const
  $columns = ReviewSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare spelerId: number
  @column()
  declare tekst: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare wedstrijdId: number | null
}

export class RittenSchema extends BaseModel {
  static $columns = ['bestuurder', 'createdAt', 'id', 'passagiers', 'updatedAt', 'vertrektijd', 'wedstrijdId'] as const
  $columns = RittenSchema.$columns
  @column()
  declare bestuurder: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare passagiers: any | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare vertrektijd: string | null
  @column()
  declare wedstrijdId: number
}

export class RoltoewijzingenSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'rol', 'spelerId', 'updatedAt', 'wedstrijdId'] as const
  $columns = RoltoewijzingenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare rol: string
  @column()
  declare spelerId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare wedstrijdId: number
}

export class SeizoenblokkenSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'naam', 'thema', 'tot', 'updatedAt', 'vanaf'] as const
  $columns = SeizoenblokkenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare naam: string
  @column()
  declare thema: string | null
  @column.date()
  declare tot: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column.date()
  declare vanaf: DateTime
}

export class SpeleropdrachtenSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'opdracht', 'spelerId', 'updatedAt', 'wedstrijdId'] as const
  $columns = SpeleropdrachtenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare opdracht: string
  @column()
  declare spelerId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare wedstrijdId: number
}

export class SpelerSchema extends BaseModel {
  static $columns = ['adres', 'beschikbaar', 'beschikbaarNotitie', 'createdAt', 'email', 'favorietBeen', 'fotoPath', 'geboortedatum', 'id', 'land', 'naam', 'positie', 'positie2', 'rugnummer', 'skills', 'stats', 'sterren', 'telefoon', 'updatedAt'] as const
  $columns = SpelerSchema.$columns
  @column()
  declare adres: string | null
  @column()
  declare beschikbaar: string
  @column()
  declare beschikbaarNotitie: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string | null
  @column()
  declare favorietBeen: string | null
  @column()
  declare fotoPath: string | null
  @column.date()
  declare geboortedatum: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare land: string | null
  @column()
  declare naam: string
  @column()
  declare positie: string | null
  @column()
  declare positie2: string | null
  @column()
  declare rugnummer: string | null
  @column()
  declare skills: any | null
  @column()
  declare stats: any | null
  @column()
  declare sterren: any | null
  @column()
  declare telefoon: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class StandrijenSchema extends BaseModel {
  static $columns = ['createdAt', 'doelTegen', 'doelVoor', 'gelijk', 'gespeeld', 'id', 'naam', 'updatedAt', 'verlies', 'winst'] as const
  $columns = StandrijenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare doelTegen: number
  @column()
  declare doelVoor: number
  @column()
  declare gelijk: number
  @column()
  declare gespeeld: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare naam: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare verlies: number
  @column()
  declare winst: number
}

export class TaaktoewijzingenSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'spelerId', 'taakId', 'updatedAt', 'wedstrijdId'] as const
  $columns = TaaktoewijzingenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare spelerId: number
  @column()
  declare taakId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare wedstrijdId: number
}

export class TactiekenSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'naam', 'tekening', 'updatedAt', 'veldType'] as const
  $columns = TactiekenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare naam: string
  @column()
  declare tekening: any | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare veldType: string
}

export class TactiekplannenSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'tekening', 'updatedAt', 'veldType', 'wedstrijdId'] as const
  $columns = TactiekplannenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tekening: any | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare veldType: string
  @column()
  declare wedstrijdId: number
}

export class TakenSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'naam', 'omschrijving', 'updatedAt'] as const
  $columns = TakenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare naam: string
  @column()
  declare omschrijving: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TenueSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'kleurPrimair', 'kleurSecundair', 'patroon', 'updatedAt'] as const
  $columns = TenueSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare kleurPrimair: string
  @column()
  declare kleurSecundair: string | null
  @column()
  declare patroon: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ToernooienSchema extends BaseModel {
  static $columns = ['createdAt', 'datum', 'id', 'locatie', 'naam', 'updatedAt'] as const
  $columns = ToernooienSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare datum: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare locatie: string | null
  @column()
  declare naam: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ToernooiteamSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'naam', 'toernooiId', 'updatedAt'] as const
  $columns = ToernooiteamSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare naam: string
  @column()
  declare toernooiId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ToernooiwedstrijdenSchema extends BaseModel {
  static $columns = ['createdAt', 'datum', 'id', 'scoreThuis', 'scoreUit', 'thuisTeamId', 'toernooiId', 'uitTeamId', 'updatedAt'] as const
  $columns = ToernooiwedstrijdenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare datum: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare scoreThuis: number | null
  @column()
  declare scoreUit: number | null
  @column()
  declare thuisTeamId: number
  @column()
  declare toernooiId: number
  @column()
  declare uitTeamId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TrainingenSchema extends BaseModel {
  static $columns = ['createdAt', 'datum', 'doelstellingen', 'duur', 'id', 'locatie', 'materialen', 'notities', 'seizoenblokId', 'tijd', 'updatedAt', 'voorbereidingen'] as const
  $columns = TrainingenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare datum: DateTime
  @column()
  declare doelstellingen: string | null
  @column()
  declare duur: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare locatie: string | null
  @column()
  declare materialen: string | null
  @column()
  declare notities: string | null
  @column()
  declare seizoenblokId: number | null
  @column()
  declare tijd: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare voorbereidingen: string | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class WedstrijdenSchema extends BaseModel {
  static $columns = ['createdAt', 'datum', 'formatie', 'id', 'locatie', 'motmSpelerId', 'notities', 'score', 'speelduur', 'status', 'tegenstander', 'thuis', 'tijd', 'updatedAt'] as const
  $columns = WedstrijdenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare datum: DateTime
  @column()
  declare formatie: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare locatie: string | null
  @column()
  declare motmSpelerId: number | null
  @column()
  declare notities: string | null
  @column()
  declare score: any | null
  @column()
  declare speelduur: number | null
  @column()
  declare status: string
  @column()
  declare tegenstander: string
  @column()
  declare thuis: boolean
  @column()
  declare tijd: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class WisselSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'inSpelerId', 'minuut', 'uitSpelerId', 'updatedAt', 'wedstrijdId'] as const
  $columns = WisselSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare inSpelerId: number
  @column()
  declare minuut: number | null
  @column()
  declare uitSpelerId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare wedstrijdId: number
}
