// Ported from legacy/fc-harlingen-app.html's FORMATIES_DATA — 29 formation
// presets with percentage-based pitch coordinates for each position slot.

export type FormatiePositie = { id: string; label: string; x: number; y: number }

export const FORMATIES: Record<string, FormatiePositie[]> = {
  '3-1-4-2': [
    { id: 'GK', label: 'DM', x: 50, y: 88 },
    { id: 'CB1', label: 'CV', x: 25, y: 74 },
    { id: 'CB2', label: 'CV', x: 50, y: 77 },
    { id: 'CB3', label: 'CV', x: 75, y: 74 },
    { id: 'DM', label: 'CVM', x: 50, y: 64 },
    { id: 'LM', label: 'LM', x: 8, y: 52 },
    { id: 'LCM', label: 'CM', x: 32, y: 51 },
    { id: 'RCM', label: 'CM', x: 68, y: 51 },
    { id: 'RM', label: 'RM', x: 92, y: 52 },
    { id: 'ST1', label: 'SP', x: 36, y: 22 },
    { id: 'ST2', label: 'SP', x: 64, y: 22 },
  ],
  '3-3-4': [
    { id: 'GK', label: 'DM', x: 50, y: 88 },
    { id: 'CB1', label: 'CV', x: 25, y: 74 },
    { id: 'CB2', label: 'CV', x: 50, y: 77 },
    { id: 'CB3', label: 'CV', x: 75, y: 74 },
    { id: 'LCM', label: 'LM', x: 22, y: 54 },
    { id: 'CM', label: 'CM', x: 50, y: 52 },
    { id: 'RCM', label: 'RM', x: 78, y: 54 },
    { id: 'LW', label: 'LVA', x: 8, y: 28 },
    { id: 'LF', label: 'SP', x: 34, y: 20 },
    { id: 'RF', label: 'SP', x: 66, y: 20 },
    { id: 'RW', label: 'RVA', x: 92, y: 28 },
  ],
  '3-4-1-2': [
    { id: 'GK', label: 'DM', x: 50, y: 88 },
    { id: 'CB1', label: 'CV', x: 25, y: 74 },
    { id: 'CB2', label: 'CV', x: 50, y: 77 },
    { id: 'CB3', label: 'CV', x: 75, y: 74 },
    { id: 'LWB', label: 'LVV', x: 8, y: 54 },
    { id: 'LCM', label: 'CM', x: 32, y: 52 },
    { id: 'RCM', label: 'CM', x: 68, y: 52 },
    { id: 'RWB', label: 'RVV', x: 92, y: 54 },
    { id: 'AM', label: 'CAM', x: 50, y: 39 },
    { id: 'ST1', label: 'SP', x: 35, y: 22 },
    { id: 'ST2', label: 'SP', x: 65, y: 22 },
  ],
  '3-4-2-1': [
    { id: 'GK', label: 'DM', x: 50, y: 88 },
    { id: 'CB1', label: 'CV', x: 25, y: 74 },
    { id: 'CB2', label: 'CV', x: 50, y: 77 },
    { id: 'CB3', label: 'CV', x: 75, y: 74 },
    { id: 'LWB', label: 'LVV', x: 8, y: 54 },
    { id: 'LCM', label: 'CM', x: 32, y: 52 },
    { id: 'RCM', label: 'CM', x: 68, y: 52 },
    { id: 'RWB', label: 'RVV', x: 92, y: 54 },
    { id: 'LAM', label: 'CAM', x: 30, y: 37 },
    { id: 'RAM', label: 'CAM', x: 70, y: 37 },
    { id: 'ST', label: 'SP', x: 50, y: 18 },
  ],
  '3-4-3A': [
    { id: 'GK', label: 'DM', x: 50, y: 88 },
    { id: 'CB1', label: 'CV', x: 25, y: 74 },
    { id: 'CB2', label: 'CV', x: 50, y: 77 },
    { id: 'CB3', label: 'CV', x: 75, y: 74 },
    { id: 'LWB', label: 'LVV', x: 8, y: 52 },
    { id: 'LCM', label: 'CM', x: 32, y: 50 },
    { id: 'RCM', label: 'CM', x: 68, y: 50 },
    { id: 'RWB', label: 'RVV', x: 92, y: 52 },
    { id: 'LW', label: 'LVA', x: 14, y: 24 },
    { id: 'ST', label: 'SP', x: 50, y: 17 },
    { id: 'RW', label: 'RVA', x: 86, y: 24 },
  ],
  '3-4-3B': [
    { id: 'GK', label: 'DM', x: 50, y: 88 },
    { id: 'CB1', label: 'CV', x: 25, y: 74 },
    { id: 'CB2', label: 'CV', x: 50, y: 77 },
    { id: 'CB3', label: 'CV', x: 75, y: 74 },
    { id: 'DM', label: 'CVM', x: 50, y: 62 },
    { id: 'LM', label: 'LM', x: 14, y: 50 },
    { id: 'RM', label: 'RM', x: 86, y: 50 },
    { id: 'AM', label: 'CAM', x: 50, y: 40 },
    { id: 'LW', label: 'LVA', x: 14, y: 24 },
    { id: 'ST', label: 'SP', x: 50, y: 17 },
    { id: 'RW', label: 'RVA', x: 86, y: 24 },
  ],
  '3-5-2': [
    { id: 'GK', label: 'DM', x: 50, y: 88 },
    { id: 'CB1', label: 'CV', x: 25, y: 74 },
    { id: 'CB2', label: 'CV', x: 50, y: 77 },
    { id: 'CB3', label: 'CV', x: 75, y: 74 },
    { id: 'LWB', label: 'LVV', x: 8, y: 52 },
    { id: 'LCM', label: 'LM', x: 30, y: 50 },
    { id: 'CM', label: 'CM', x: 50, y: 48 },
    { id: 'RCM', label: 'RM', x: 70, y: 50 },
    { id: 'RWB', label: 'RVV', x: 92, y: 52 },
    { id: 'ST1', label: 'SP', x: 34, y: 22 },
    { id: 'ST2', label: 'SP', x: 66, y: 22 },
  ],
  '4-1-2-1-2A': [
    { id: 'GK', label: 'DM', x: 50, y: 88 },
    { id: 'LB', label: 'LV', x: 14, y: 72 },
    { id: 'CB1', label: 'CV', x: 37, y: 76 },
    { id: 'CB2', label: 'CV', x: 63, y: 76 },
    { id: 'RB', label: 'RV', x: 86, y: 72 },
    { id: 'DM', label: 'CVM', x: 50, y: 62 },
    { id: 'LCM', label: 'CM', x: 34, y: 51 },
    { id: 'RCM', label: 'CM', x: 66, y: 51 },
    { id: 'AM', label: 'CAM', x: 50, y: 39 },
    { id: 'ST1', label: 'SP', x: 35, y: 22 },
    { id: 'ST2', label: 'SP', x: 65, y: 22 },
  ],
  '4-1-2-1-2B': [
    { id: 'GK', label: 'DM', x: 50, y: 88 },
    { id: 'LB', label: 'LV', x: 14, y: 72 },
    { id: 'CB1', label: 'CV', x: 37, y: 76 },
    { id: 'CB2', label: 'CV', x: 63, y: 76 },
    { id: 'RB', label: 'RV', x: 86, y: 72 },
    { id: 'DM', label: 'CVM', x: 50, y: 62 },
    { id: 'LCM', label: 'CM', x: 22, y: 51 },
    { id: 'RCM', label: 'CM', x: 78, y: 51 },
    { id: 'AM', label: 'CAM', x: 50, y: 39 },
    { id: 'ST1', label: 'SP', x: 35, y: 22 },
    { id: 'ST2', label: 'SP', x: 65, y: 22 },
  ],
  '4-1-3-2': [
    { id: 'GK', label: 'DM', x: 50, y: 88 },
    { id: 'LB', label: 'LV', x: 14, y: 72 },
    { id: 'CB1', label: 'CV', x: 37, y: 76 },
    { id: 'CB2', label: 'CV', x: 63, y: 76 },
    { id: 'RB', label: 'RV', x: 86, y: 72 },
    { id: 'DM', label: 'CVM', x: 50, y: 62 },
    { id: 'LM', label: 'LM', x: 20, y: 49 },
    { id: 'CM', label: 'CM', x: 50, y: 49 },
    { id: 'RM', label: 'RM', x: 80, y: 49 },
    { id: 'ST1', label: 'SP', x: 35, y: 22 },
    { id: 'ST2', label: 'SP', x: 65, y: 22 },
  ],
  '4-1-4-1': [
    { id: 'GK', label: 'DM', x: 50, y: 88 },
    { id: 'LB', label: 'LV', x: 14, y: 72 },
    { id: 'CB1', label: 'CV', x: 37, y: 76 },
    { id: 'CB2', label: 'CV', x: 63, y: 76 },
    { id: 'RB', label: 'RV', x: 86, y: 72 },
    { id: 'DM', label: 'CVM', x: 50, y: 60 },
    { id: 'LM', label: 'LM', x: 10, y: 44 },
    { id: 'LCM', label: 'CM', x: 34, y: 44 },
    { id: 'RCM', label: 'CM', x: 66, y: 44 },
    { id: 'RM', label: 'RM', x: 90, y: 44 },
    { id: 'ST', label: 'SP', x: 50, y: 18 },
  ],
  '4-2-1-3': [
    { id: 'GK', label: 'DM', x: 50, y: 88 },
    { id: 'LB', label: 'LV', x: 14, y: 72 },
    { id: 'CB1', label: 'CV', x: 37, y: 76 },
    { id: 'CB2', label: 'CV', x: 63, y: 76 },
    { id: 'RB', label: 'RV', x: 86, y: 72 },
    { id: 'DM1', label: 'CVM', x: 36, y: 59 },
    { id: 'DM2', label: 'CVM', x: 64, y: 59 },
    { id: 'AM', label: 'CAM', x: 50, y: 43 },
    { id: 'LW', label: 'LVA', x: 14, y: 24 },
    { id: 'ST', label: 'SP', x: 50, y: 18 },
    { id: 'RW', label: 'RVA', x: 86, y: 24 },
  ],
  '4-2-2-2': [
    { id: 'GK', label: 'DM', x: 50, y: 88 },
    { id: 'LB', label: 'LV', x: 14, y: 72 },
    { id: 'CB1', label: 'CV', x: 37, y: 76 },
    { id: 'CB2', label: 'CV', x: 63, y: 76 },
    { id: 'RB', label: 'RV', x: 86, y: 72 },
    { id: 'DM1', label: 'CVM', x: 36, y: 59 },
    { id: 'DM2', label: 'CVM', x: 64, y: 59 },
    { id: 'LM', label: 'LM', x: 18, y: 45 },
    { id: 'RM', label: 'RM', x: 82, y: 45 },
    { id: 'ST1', label: 'SP', x: 35, y: 22 },
    { id: 'ST2', label: 'SP', x: 65, y: 22 },
  ],
  '4-2-3-1A': [
    { id: 'GK', label: 'DM', x: 50, y: 88 },
    { id: 'LB', label: 'LV', x: 14, y: 72 },
    { id: 'CB1', label: 'CV', x: 37, y: 76 },
    { id: 'CB2', label: 'CV', x: 63, y: 76 },
    { id: 'RB', label: 'RV', x: 86, y: 72 },
    { id: 'DM1', label: 'CVM', x: 36, y: 58 },
    { id: 'DM2', label: 'CVM', x: 64, y: 58 },
    { id: 'LW', label: 'LVA', x: 14, y: 37 },
    { id: 'AM', label: 'CAM', x: 50, y: 36 },
    { id: 'RW', label: 'RVA', x: 86, y: 37 },
    { id: 'ST', label: 'SP', x: 50, y: 18 },
  ],
  '4-2-3-1B': [
    { id: 'GK', label: 'DM', x: 50, y: 88 },
    { id: 'LB', label: 'LV', x: 14, y: 72 },
    { id: 'CB1', label: 'CV', x: 37, y: 76 },
    { id: 'CB2', label: 'CV', x: 63, y: 76 },
    { id: 'RB', label: 'RV', x: 86, y: 72 },
    { id: 'DM1', label: 'CVM', x: 36, y: 60 },
    { id: 'DM2', label: 'CVM', x: 64, y: 60 },
    { id: 'LAM', label: 'CAM', x: 26, y: 44 },
    { id: 'CAM', label: 'CAM', x: 50, y: 43 },
    { id: 'RAM', label: 'CAM', x: 74, y: 44 },
    { id: 'ST', label: 'SP', x: 50, y: 18 },
  ],
  '4-2-4': [
    { id: 'GK', label: 'DM', x: 50, y: 88 },
    { id: 'LB', label: 'LV', x: 14, y: 72 },
    { id: 'CB1', label: 'CV', x: 37, y: 76 },
    { id: 'CB2', label: 'CV', x: 63, y: 76 },
    { id: 'RB', label: 'RV', x: 86, y: 72 },
    { id: 'DM1', label: 'CVM', x: 36, y: 56 },
    { id: 'DM2', label: 'CVM', x: 64, y: 56 },
    { id: 'LW', label: 'LVA', x: 8, y: 28 },
    { id: 'LF', label: 'SP', x: 34, y: 20 },
    { id: 'RF', label: 'SP', x: 66, y: 20 },
    { id: 'RW', label: 'RVA', x: 92, y: 28 },
  ],
  '4-3-3A': [
    { id: 'GK', label: 'DM', x: 50, y: 88 },
    { id: 'LB', label: 'LV', x: 14, y: 72 },
    { id: 'CB1', label: 'CV', x: 37, y: 76 },
    { id: 'CB2', label: 'CV', x: 63, y: 76 },
    { id: 'RB', label: 'RV', x: 86, y: 72 },
    { id: 'DM', label: 'CVM', x: 50, y: 57 },
    { id: 'LAM', label: 'CAM', x: 26, y: 44 },
    { id: 'RAM', label: 'CAM', x: 74, y: 44 },
    { id: 'LW', label: 'LVA', x: 13, y: 22 },
    { id: 'ST', label: 'SP', x: 50, y: 15 },
    { id: 'RW', label: 'RVA', x: 87, y: 22 },
  ],
  '4-3-3B': [
    { id: 'GK', label: 'DM', x: 50, y: 88 },
    { id: 'LB', label: 'LV', x: 14, y: 72 },
    { id: 'CB1', label: 'CV', x: 37, y: 76 },
    { id: 'CB2', label: 'CV', x: 63, y: 76 },
    { id: 'RB', label: 'RV', x: 86, y: 72 },
    { id: 'DM1', label: 'CVM', x: 33, y: 57 },
    { id: 'DM2', label: 'CVM', x: 67, y: 57 },
    { id: 'AM', label: 'CAM', x: 50, y: 43 },
    { id: 'LW', label: 'LVA', x: 13, y: 22 },
    { id: 'ST', label: 'SP', x: 50, y: 15 },
    { id: 'RW', label: 'RVA', x: 87, y: 22 },
  ],
  '4-4-1-1': [
    { id: 'GK', label: 'DM', x: 50, y: 88 },
    { id: 'LB', label: 'LV', x: 14, y: 72 },
    { id: 'CB1', label: 'CV', x: 37, y: 76 },
    { id: 'CB2', label: 'CV', x: 63, y: 76 },
    { id: 'RB', label: 'RV', x: 86, y: 72 },
    { id: 'LM', label: 'LM', x: 10, y: 52 },
    { id: 'LCM', label: 'CM', x: 35, y: 53 },
    { id: 'RCM', label: 'CM', x: 65, y: 53 },
    { id: 'RM', label: 'RM', x: 90, y: 52 },
    { id: 'SS', label: 'CAM', x: 50, y: 35 },
    { id: 'ST', label: 'SP', x: 50, y: 18 },
  ],
  '4-4-2A': [
    { id: 'GK', label: 'DM', x: 50, y: 88 },
    { id: 'LB', label: 'LV', x: 14, y: 72 },
    { id: 'CB1', label: 'CV', x: 37, y: 76 },
    { id: 'CB2', label: 'CV', x: 63, y: 76 },
    { id: 'RB', label: 'RV', x: 86, y: 72 },
    { id: 'LM', label: 'LM', x: 10, y: 52 },
    { id: 'LCM', label: 'CM', x: 37, y: 53 },
    { id: 'RCM', label: 'CM', x: 63, y: 53 },
    { id: 'RM', label: 'RM', x: 90, y: 52 },
    { id: 'ST1', label: 'SP', x: 36, y: 22 },
    { id: 'ST2', label: 'SP', x: 64, y: 22 },
  ],
  '4-4-2B': [
    { id: 'GK', label: 'DM', x: 50, y: 88 },
    { id: 'LB', label: 'LV', x: 14, y: 72 },
    { id: 'CB1', label: 'CV', x: 37, y: 76 },
    { id: 'CB2', label: 'CV', x: 63, y: 76 },
    { id: 'RB', label: 'RV', x: 86, y: 72 },
    { id: 'DM', label: 'CVM', x: 50, y: 60 },
    { id: 'LM', label: 'LM', x: 13, y: 49 },
    { id: 'RM', label: 'RM', x: 87, y: 49 },
    { id: 'AM', label: 'CAM', x: 50, y: 38 },
    { id: 'ST1', label: 'SP', x: 35, y: 22 },
    { id: 'ST2', label: 'SP', x: 65, y: 22 },
  ],
  '4-5-1A': [
    { id: 'GK', label: 'DM', x: 50, y: 88 },
    { id: 'LB', label: 'LV', x: 14, y: 72 },
    { id: 'CB1', label: 'CV', x: 37, y: 76 },
    { id: 'CB2', label: 'CV', x: 63, y: 76 },
    { id: 'RB', label: 'RV', x: 86, y: 72 },
    { id: 'LM', label: 'LM', x: 8, y: 50 },
    { id: 'LCM', label: 'CM', x: 28, y: 52 },
    { id: 'CM', label: 'CM', x: 50, y: 50 },
    { id: 'RCM', label: 'CM', x: 72, y: 52 },
    { id: 'RM', label: 'RM', x: 92, y: 50 },
    { id: 'ST', label: 'SP', x: 50, y: 18 },
  ],
  '4-5-1B': [
    { id: 'GK', label: 'DM', x: 50, y: 88 },
    { id: 'LB', label: 'LV', x: 14, y: 72 },
    { id: 'CB1', label: 'CV', x: 37, y: 76 },
    { id: 'CB2', label: 'CV', x: 63, y: 76 },
    { id: 'RB', label: 'RV', x: 86, y: 72 },
    { id: 'DM1', label: 'CVM', x: 34, y: 60 },
    { id: 'DM2', label: 'CVM', x: 66, y: 60 },
    { id: 'LM', label: 'LM', x: 10, y: 48 },
    { id: 'CM', label: 'CM', x: 50, y: 50 },
    { id: 'RM', label: 'RM', x: 90, y: 48 },
    { id: 'ST', label: 'SP', x: 50, y: 18 },
  ],
  '5-2-1-2': [
    { id: 'GK', label: 'DM', x: 50, y: 88 },
    { id: 'LWB', label: 'LVV', x: 8, y: 70 },
    { id: 'CB1', label: 'CV', x: 26, y: 76 },
    { id: 'CB2', label: 'CV', x: 50, y: 78 },
    { id: 'CB3', label: 'CV', x: 74, y: 76 },
    { id: 'RWB', label: 'RVV', x: 92, y: 70 },
    { id: 'DM1', label: 'CVM', x: 36, y: 57 },
    { id: 'DM2', label: 'CVM', x: 64, y: 57 },
    { id: 'AM', label: 'CAM', x: 50, y: 42 },
    { id: 'ST1', label: 'SP', x: 35, y: 22 },
    { id: 'ST2', label: 'SP', x: 65, y: 22 },
  ],
  '5-2-3': [
    { id: 'GK', label: 'DM', x: 50, y: 88 },
    { id: 'LWB', label: 'LVV', x: 8, y: 70 },
    { id: 'CB1', label: 'CV', x: 26, y: 76 },
    { id: 'CB2', label: 'CV', x: 50, y: 78 },
    { id: 'CB3', label: 'CV', x: 74, y: 76 },
    { id: 'RWB', label: 'RVV', x: 92, y: 70 },
    { id: 'CM1', label: 'CM', x: 34, y: 52 },
    { id: 'CM2', label: 'CM', x: 66, y: 52 },
    { id: 'LW', label: 'LVA', x: 14, y: 24 },
    { id: 'ST', label: 'SP', x: 50, y: 18 },
    { id: 'RW', label: 'RVA', x: 86, y: 24 },
  ],
  '5-3-2A': [
    { id: 'GK', label: 'DM', x: 50, y: 88 },
    { id: 'LWB', label: 'LVV', x: 8, y: 70 },
    { id: 'CB1', label: 'CV', x: 26, y: 76 },
    { id: 'CB2', label: 'CV', x: 50, y: 78 },
    { id: 'CB3', label: 'CV', x: 74, y: 76 },
    { id: 'RWB', label: 'RVV', x: 92, y: 70 },
    { id: 'LCM', label: 'LM', x: 24, y: 50 },
    { id: 'CM', label: 'CM', x: 50, y: 48 },
    { id: 'RCM', label: 'RM', x: 76, y: 50 },
    { id: 'ST1', label: 'SP', x: 34, y: 20 },
    { id: 'ST2', label: 'SP', x: 66, y: 20 },
  ],
  '5-3-2B': [
    { id: 'GK', label: 'DM', x: 50, y: 88 },
    { id: 'LWB', label: 'LVV', x: 8, y: 70 },
    { id: 'CB1', label: 'CV', x: 26, y: 76 },
    { id: 'CB2', label: 'CV', x: 50, y: 78 },
    { id: 'CB3', label: 'CV', x: 74, y: 76 },
    { id: 'RWB', label: 'RVV', x: 92, y: 70 },
    { id: 'DM', label: 'CVM', x: 50, y: 58 },
    { id: 'LCM', label: 'CM', x: 28, y: 47 },
    { id: 'RCM', label: 'CM', x: 72, y: 47 },
    { id: 'ST1', label: 'SP', x: 35, y: 22 },
    { id: 'ST2', label: 'SP', x: 65, y: 22 },
  ],
  '5-4-1A': [
    { id: 'GK', label: 'DM', x: 50, y: 88 },
    { id: 'LWB', label: 'LVV', x: 8, y: 70 },
    { id: 'CB1', label: 'CV', x: 26, y: 76 },
    { id: 'CB2', label: 'CV', x: 50, y: 78 },
    { id: 'CB3', label: 'CV', x: 74, y: 76 },
    { id: 'RWB', label: 'RVV', x: 92, y: 70 },
    { id: 'LM', label: 'LM', x: 10, y: 52 },
    { id: 'LCM', label: 'CM', x: 34, y: 52 },
    { id: 'RCM', label: 'CM', x: 66, y: 52 },
    { id: 'RM', label: 'RM', x: 90, y: 52 },
    { id: 'ST', label: 'SP', x: 50, y: 18 },
  ],
  '5-4-1B': [
    { id: 'GK', label: 'DM', x: 50, y: 88 },
    { id: 'LWB', label: 'LVV', x: 8, y: 70 },
    { id: 'CB1', label: 'CV', x: 26, y: 76 },
    { id: 'CB2', label: 'CV', x: 50, y: 78 },
    { id: 'CB3', label: 'CV', x: 74, y: 76 },
    { id: 'RWB', label: 'RVV', x: 92, y: 70 },
    { id: 'DM', label: 'CVM', x: 50, y: 60 },
    { id: 'LM', label: 'LM', x: 14, y: 50 },
    { id: 'RM', label: 'RM', x: 86, y: 50 },
    { id: 'AM', label: 'CAM', x: 50, y: 40 },
    { id: 'ST', label: 'SP', x: 50, y: 20 },
  ],
}

export const FORMATIE_NAMEN = Object.keys(FORMATIES)
